apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7 ## nicolasandrescalvo/mysql-dh:1.0
        name: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: somewordpress
          - name:  MYSQL_DATABASE
            value: wordpress
          - name:  MYSQL_USER
            value: wordpress
          - name:  MYSQL_PASSWORD
            value: wordpress
        resources: {}